import time
from selenium.webdriver.common.by import By

class Add_Next:
    def __init__(self,driver):
        self.driver = driver
        self.add_Next_button = (By.XPATH,"//button[normalize-space()='Next']")
        self.select_course = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[1]/select[1]")
        self.select_option_course = (By.XPATH,"(//option[@value='14'][normalize-space()='Quality Assurance Training with AI'])[1]")
        self.select_batch = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[2]/select[1]")
        self.select_batch_option = (By.XPATH,"(//option[@value='17'][normalize-space()='Shrawan'])[1]")
        self.select_date = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[3]/input[1]")
        self.select_date_option = (By.XPATH,"(//input[@name='startingDate'])[1]")
        self.select_mode = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[4]/select[1]")
        self.select_mode_option = (By.XPATH,"(//option[normalize-space()='Online'])[1]")
        self.select_time = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[5]/select[1]")
        self.select_time_option = (By.XPATH,"(//option[normalize-space()='7:00 - 8:00 AM'])[1]")
        self.select_lead = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[6]/select[1]")
        self.select_lead_option = (By.XPATH,"(//option[@value='1'][normalize-space()='Direct'])[1]")

        self.select_current_stage = (By.XPATH,"/html[1]/body[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/form[1]/div[1]/div[7]/select[1]")
        self.select_stage_option = (By.XPATH,"(//option[normalize-space()='Booking'])[1]")
        # self.lead = (By.XPATH,"//input[@name='lead']")
        # self.lead_option = (By.XPATH,"//option[@value='3']")
        self.next_button = (By.XPATH,"//button[normalize-space()='Next']")
        self.previous = (By.XPATH,"//button[normalize-space()='Previous']")
        self.discard = (By.XPATH,"//button[normalize-space()='Discard']")

    def enter_next_button(self):
        self.driver.find_element(*self.add_Next_button).click()
        time.sleep(2)

    def fill_next_info(self):
        self.driver.find_element(*self.select_course).click()
        time.sleep(2)
        self.driver.find_element(*self.select_option_course).click()
        time.sleep(2)
        self.driver.find_element(*self.select_batch).click()
        time.sleep(2)
        self.driver.find_element(*self.select_batch_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_date).send_keys("05/01/2026")
        time.sleep(2)
        self.driver.find_element(*self.select_mode).click()
        time.sleep(2)
        self.driver.find_element(*self.select_mode_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_time).click()
        time.sleep(2)
        self.driver.find_element(*self.select_time_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_lead).click()
        time.sleep(2)
        self.driver.find_element(*self.select_lead_option).click()
        time.sleep(2)
        # self.driver.find_element(*self.select_stage).click()
        time.sleep(2)
        self.driver.find_element(*self.select_current_stage).click()
        time.sleep(2)
        self.driver.find_element(*self.select_stage_option).click()
        time.sleep(2)
        self.driver.find_element(*self.next_button).click()
        time.sleep(2)
        self.driver.find_element(*self.previous).click()
        time.sleep(2)
        self.driver.find_element(*self.previous).click()
        time.sleep(2)
        self.driver.find_element(*self.discard).click()
        time.sleep(2)

    def fill_next_info1(self):
        self.driver.find_element(*self.select_course).click()
        time.sleep(2)
        self.driver.find_element(*self.select_option_course).click()
        time.sleep(2)
        self.driver.find_element(*self.select_batch).click()
        time.sleep(2)
        self.driver.find_element(*self.select_batch_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_date).send_keys("05/01/2026")
        time.sleep(2)
        self.driver.find_element(*self.select_mode).click()
        time.sleep(2)
        self.driver.find_element(*self.select_mode_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_time).click()
        time.sleep(2)
        self.driver.find_element(*self.select_time_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_lead).click()
        time.sleep(2)
        self.driver.find_element(*self.select_lead_option).click()
        time.sleep(2)
        self.driver.find_element(*self.select_current_stage).click()
        time.sleep(2)
        self.driver.find_element(*self.select_stage_option).click()
        time.sleep(2)
        self.driver.find_element(*self.next_button).click()
        time.sleep(2)
